export const COUNTRY_MODEL = 'COUNTRY_REPOSITORY';
export const OPERATOR_MODEL = 'OPERATOR_REPOSITORY';
export const CALL_RECORD_MODEL = 'CALL_RECORD_REPOSITORY';
export const PREFIX_MODEL = 'PREFIX_REPOSITORY';
