export const Operators = [
  { name: 'A-Mobile' },
  { name: 'Aquafon' },
  { name: 'Sukhumi' },
  { name: 'Herat' },
  { name: 'Jalalabad' },
  { name: 'Kabul' },
  { name: 'Kandahar' },
  { name: 'Areeba/MTN' },
  { name: 'AWCC' },
  { name: 'CDMA' },
  { name: 'Etisalat' },
  { name: 'Roshan' },
  { name: 'Roshan_1' },
  { name: 'Salaam' },
  { name: 'Wasel' },
  { name: 'AMC' },
  { name: 'Albtel' },
  { name: 'Interactive TV' },
  { name: 'Eagle' },
  { name: 'Plus/4L' },
  { name: 'Vodafone' },
  { name: 'OLO' },
  { name: '' },
  { name: '' },
  { name: '' },
  { name: '' },
  { name: 'Special Services' },
  { name: 'Others' },
];
